### ISSUE TITLE
Assertions for only a tagName or a landmarkRole?

### ISSUE THREAD

**Issue by ksin** [ember-a11y/ember-a11y-landmarks#7]
Is this assertion correct?
https://github.com/MelSumner/ember-a11y-landmarks/blob/master/addon/components/a11y-landmark.js#L77

How can a user specify a `div` that has a `"navigation"` role? I thought a `div` can have any role (except `"search"`). Or is that not recommended?

**Comment by EndangeredMassa** [comment]
Resolved by: https://github.com/ember-a11y/ember-a11y-landmarks/pull/11
