### ISSUE TITLE
Default use of component throws error

### ISSUE THREAD

**Issue by ksin** [ember-a11y/ember-a11y-landmarks#8]
Using the component with nothing passed in throws an error:
https://github.com/MelSumner/ember-a11y-landmarks/blob/master/addon/components/a11y-landmark.js#L86

That seems weird for ease-of-usage to me. Shouldn't it be a `'div'` with role `'region'` by default?

**Comment by MelSumner** [comment]
@ksin it used to, so I need to see what changed to disallow it.

**Comment by MelSumner** [comment]
@EndangeredMassa would you have time to look into this?

**Comment by EndangeredMassa** [comment]
It did indeed, but in my refactoring that was removed.

@MelSumner: Do we want that to be the default? We can definitely change it.

**Comment by EndangeredMassa** [comment]
Resolved by: https://github.com/ember-a11y/ember-a11y-landmarks/pull/11
